#include <graphx.h>
#include "gfx/gfx.h"
#include "gfx/offsets/offsets.h"
#include "tank.h"

#define tank_sprite_total_width 28
#define tank_sprite_total_height 24

gfx_UninitedSprite(pl_base_9, pl_base_7_width, pl_base_7_height);
gfx_UninitedSprite(pl_base_10, pl_base_6_width, pl_base_6_height);
gfx_UninitedSprite(pl_base_11, pl_base_5_width, pl_base_5_height);
gfx_UninitedSprite(pl_base_12, pl_base_4_width, pl_base_4_height);
gfx_UninitedSprite(pl_base_13, pl_base_3_width, pl_base_3_height);
gfx_UninitedSprite(pl_base_14, pl_base_2_width, pl_base_2_height);
gfx_UninitedSprite(pl_base_15, pl_base_1_width, pl_base_1_height);

gfx_UninitedSprite(pl_turret_9, pl_turret_7_width, pl_turret_7_height);
gfx_UninitedSprite(pl_turret_10, pl_turret_6_width, pl_turret_6_height);
gfx_UninitedSprite(pl_turret_11, pl_turret_5_width, pl_turret_5_height);
gfx_UninitedSprite(pl_turret_12, pl_turret_4_width, pl_turret_4_height);
gfx_UninitedSprite(pl_turret_13, pl_turret_3_width, pl_turret_3_height);
gfx_UninitedSprite(pl_turret_14, pl_turret_2_width, pl_turret_2_height);
gfx_UninitedSprite(pl_turret_15, pl_turret_1_width, pl_turret_1_height);

struct {
    uint8_t base_0_data[en_base_0_size];
    uint8_t base_1_data[en_base_1_size];
    uint8_t base_2_data[en_base_2_size];
    uint8_t base_3_data[en_base_3_size];
    uint8_t base_4_data[en_base_4_size];
    uint8_t base_5_data[en_base_5_size];
    uint8_t base_6_data[en_base_6_size];
    uint8_t base_7_data[en_base_7_size];
    uint8_t base_8_data[en_base_8_size];
    uint8_t base_9_data[en_base_7_size];
    uint8_t base_10_data[en_base_6_size];
    uint8_t base_11_data[en_base_5_size];
    uint8_t base_12_data[en_base_4_size];
    uint8_t base_13_data[en_base_3_size];
    uint8_t base_14_data[en_base_2_size];
    uint8_t base_15_data[en_base_1_size];

    uint8_t turret_0_data[en_turret_0_size];
    uint8_t turret_1_data[en_turret_1_size];
    uint8_t turret_2_data[en_turret_2_size];
    uint8_t turret_3_data[en_turret_3_size];
    uint8_t turret_4_data[en_turret_4_size];
    uint8_t turret_5_data[en_turret_5_size];
    uint8_t turret_6_data[en_turret_6_size];
    uint8_t turret_7_data[en_turret_7_size];
    uint8_t turret_8_data[en_turret_8_size];
    uint8_t turret_9_data[en_turret_7_size];
    uint8_t turret_10_data[en_turret_6_size];
    uint8_t turret_11_data[en_turret_5_size];
    uint8_t turret_12_data[en_turret_4_size];
    uint8_t turret_13_data[en_turret_3_size];
    uint8_t turret_14_data[en_turret_2_size];
    uint8_t turret_15_data[en_turret_1_size];
} enemy_tank_sprites[NUM_TANK_TYPES - 1];

gfx_sprite_t * const tank_bases[NUM_TANK_TYPES][16] = {
        {
                pl_base_0,
                pl_base_1,
                pl_base_2,
                pl_base_3,
                pl_base_4,
                pl_base_5,
                pl_base_6,
                pl_base_7,
                pl_base_8,
                (gfx_sprite_t*)pl_base_9_data,
                (gfx_sprite_t*)pl_base_10_data,
                (gfx_sprite_t*)pl_base_11_data,
                (gfx_sprite_t*)pl_base_12_data,
                (gfx_sprite_t*)pl_base_13_data,
                (gfx_sprite_t*)pl_base_14_data,
                (gfx_sprite_t*)pl_base_15_data,
        },
        {
                (gfx_sprite_t*)enemy_tank_sprites[0].base_0_data,
                (gfx_sprite_t*)enemy_tank_sprites[0].base_1_data,
                (gfx_sprite_t*)enemy_tank_sprites[0].base_2_data,
                (gfx_sprite_t*)enemy_tank_sprites[0].base_3_data,
                (gfx_sprite_t*)enemy_tank_sprites[0].base_4_data,
                (gfx_sprite_t*)enemy_tank_sprites[0].base_5_data,
                (gfx_sprite_t*)enemy_tank_sprites[0].base_6_data,
                (gfx_sprite_t*)enemy_tank_sprites[0].base_7_data,
                (gfx_sprite_t*)enemy_tank_sprites[0].base_8_data,
                (gfx_sprite_t*)enemy_tank_sprites[0].base_9_data,
                (gfx_sprite_t*)enemy_tank_sprites[0].base_10_data,
                (gfx_sprite_t*)enemy_tank_sprites[0].base_11_data,
                (gfx_sprite_t*)enemy_tank_sprites[0].base_12_data,
                (gfx_sprite_t*)enemy_tank_sprites[0].base_13_data,
                (gfx_sprite_t*)enemy_tank_sprites[0].base_14_data,
                (gfx_sprite_t*)enemy_tank_sprites[0].base_15_data,
        },
        {
                (gfx_sprite_t*)enemy_tank_sprites[1].base_0_data,
                (gfx_sprite_t*)enemy_tank_sprites[1].base_1_data,
                (gfx_sprite_t*)enemy_tank_sprites[1].base_2_data,
                (gfx_sprite_t*)enemy_tank_sprites[1].base_3_data,
                (gfx_sprite_t*)enemy_tank_sprites[1].base_4_data,
                (gfx_sprite_t*)enemy_tank_sprites[1].base_5_data,
                (gfx_sprite_t*)enemy_tank_sprites[1].base_6_data,
                (gfx_sprite_t*)enemy_tank_sprites[1].base_7_data,
                (gfx_sprite_t*)enemy_tank_sprites[1].base_8_data,
                (gfx_sprite_t*)enemy_tank_sprites[1].base_9_data,
                (gfx_sprite_t*)enemy_tank_sprites[1].base_10_data,
                (gfx_sprite_t*)enemy_tank_sprites[1].base_11_data,
                (gfx_sprite_t*)enemy_tank_sprites[1].base_12_data,
                (gfx_sprite_t*)enemy_tank_sprites[1].base_13_data,
                (gfx_sprite_t*)enemy_tank_sprites[1].base_14_data,
                (gfx_sprite_t*)enemy_tank_sprites[1].base_15_data,
        },
        {
                (gfx_sprite_t*)enemy_tank_sprites[2].base_0_data,
                (gfx_sprite_t*)enemy_tank_sprites[2].base_1_data,
                (gfx_sprite_t*)enemy_tank_sprites[2].base_2_data,
                (gfx_sprite_t*)enemy_tank_sprites[2].base_3_data,
                (gfx_sprite_t*)enemy_tank_sprites[2].base_4_data,
                (gfx_sprite_t*)enemy_tank_sprites[2].base_5_data,
                (gfx_sprite_t*)enemy_tank_sprites[2].base_6_data,
                (gfx_sprite_t*)enemy_tank_sprites[2].base_7_data,
                (gfx_sprite_t*)enemy_tank_sprites[2].base_8_data,
                (gfx_sprite_t*)enemy_tank_sprites[2].base_9_data,
                (gfx_sprite_t*)enemy_tank_sprites[2].base_10_data,
                (gfx_sprite_t*)enemy_tank_sprites[2].base_11_data,
                (gfx_sprite_t*)enemy_tank_sprites[2].base_12_data,
                (gfx_sprite_t*)enemy_tank_sprites[2].base_13_data,
                (gfx_sprite_t*)enemy_tank_sprites[2].base_14_data,
                (gfx_sprite_t*)enemy_tank_sprites[2].base_15_data,
        },
        {
                (gfx_sprite_t*)enemy_tank_sprites[3].base_0_data,
                (gfx_sprite_t*)enemy_tank_sprites[3].base_1_data,
                (gfx_sprite_t*)enemy_tank_sprites[3].base_2_data,
                (gfx_sprite_t*)enemy_tank_sprites[3].base_3_data,
                (gfx_sprite_t*)enemy_tank_sprites[3].base_4_data,
                (gfx_sprite_t*)enemy_tank_sprites[3].base_5_data,
                (gfx_sprite_t*)enemy_tank_sprites[3].base_6_data,
                (gfx_sprite_t*)enemy_tank_sprites[3].base_7_data,
                (gfx_sprite_t*)enemy_tank_sprites[3].base_8_data,
                (gfx_sprite_t*)enemy_tank_sprites[3].base_9_data,
                (gfx_sprite_t*)enemy_tank_sprites[3].base_10_data,
                (gfx_sprite_t*)enemy_tank_sprites[3].base_11_data,
                (gfx_sprite_t*)enemy_tank_sprites[3].base_12_data,
                (gfx_sprite_t*)enemy_tank_sprites[3].base_13_data,
                (gfx_sprite_t*)enemy_tank_sprites[3].base_14_data,
                (gfx_sprite_t*)enemy_tank_sprites[3].base_15_data,
        },
        {
                (gfx_sprite_t*)enemy_tank_sprites[4].base_0_data,
                (gfx_sprite_t*)enemy_tank_sprites[4].base_1_data,
                (gfx_sprite_t*)enemy_tank_sprites[4].base_2_data,
                (gfx_sprite_t*)enemy_tank_sprites[4].base_3_data,
                (gfx_sprite_t*)enemy_tank_sprites[4].base_4_data,
                (gfx_sprite_t*)enemy_tank_sprites[4].base_5_data,
                (gfx_sprite_t*)enemy_tank_sprites[4].base_6_data,
                (gfx_sprite_t*)enemy_tank_sprites[4].base_7_data,
                (gfx_sprite_t*)enemy_tank_sprites[4].base_8_data,
                (gfx_sprite_t*)enemy_tank_sprites[4].base_9_data,
                (gfx_sprite_t*)enemy_tank_sprites[4].base_10_data,
                (gfx_sprite_t*)enemy_tank_sprites[4].base_11_data,
                (gfx_sprite_t*)enemy_tank_sprites[4].base_12_data,
                (gfx_sprite_t*)enemy_tank_sprites[4].base_13_data,
                (gfx_sprite_t*)enemy_tank_sprites[4].base_14_data,
                (gfx_sprite_t*)enemy_tank_sprites[4].base_15_data,
        },
        {
                (gfx_sprite_t*)enemy_tank_sprites[5].base_0_data,
                (gfx_sprite_t*)enemy_tank_sprites[5].base_1_data,
                (gfx_sprite_t*)enemy_tank_sprites[5].base_2_data,
                (gfx_sprite_t*)enemy_tank_sprites[5].base_3_data,
                (gfx_sprite_t*)enemy_tank_sprites[5].base_4_data,
                (gfx_sprite_t*)enemy_tank_sprites[5].base_5_data,
                (gfx_sprite_t*)enemy_tank_sprites[5].base_6_data,
                (gfx_sprite_t*)enemy_tank_sprites[5].base_7_data,
                (gfx_sprite_t*)enemy_tank_sprites[5].base_8_data,
                (gfx_sprite_t*)enemy_tank_sprites[5].base_9_data,
                (gfx_sprite_t*)enemy_tank_sprites[5].base_10_data,
                (gfx_sprite_t*)enemy_tank_sprites[5].base_11_data,
                (gfx_sprite_t*)enemy_tank_sprites[5].base_12_data,
                (gfx_sprite_t*)enemy_tank_sprites[5].base_13_data,
                (gfx_sprite_t*)enemy_tank_sprites[5].base_14_data,
                (gfx_sprite_t*)enemy_tank_sprites[5].base_15_data,
        },
        {
                (gfx_sprite_t*)enemy_tank_sprites[6].base_0_data,
                (gfx_sprite_t*)enemy_tank_sprites[6].base_1_data,
                (gfx_sprite_t*)enemy_tank_sprites[6].base_2_data,
                (gfx_sprite_t*)enemy_tank_sprites[6].base_3_data,
                (gfx_sprite_t*)enemy_tank_sprites[6].base_4_data,
                (gfx_sprite_t*)enemy_tank_sprites[6].base_5_data,
                (gfx_sprite_t*)enemy_tank_sprites[6].base_6_data,
                (gfx_sprite_t*)enemy_tank_sprites[6].base_7_data,
                (gfx_sprite_t*)enemy_tank_sprites[6].base_8_data,
                (gfx_sprite_t*)enemy_tank_sprites[6].base_9_data,
                (gfx_sprite_t*)enemy_tank_sprites[6].base_10_data,
                (gfx_sprite_t*)enemy_tank_sprites[6].base_11_data,
                (gfx_sprite_t*)enemy_tank_sprites[6].base_12_data,
                (gfx_sprite_t*)enemy_tank_sprites[6].base_13_data,
                (gfx_sprite_t*)enemy_tank_sprites[6].base_14_data,
                (gfx_sprite_t*)enemy_tank_sprites[6].base_15_data,
        },
        {
                (gfx_sprite_t*)enemy_tank_sprites[7].base_0_data,
                (gfx_sprite_t*)enemy_tank_sprites[7].base_1_data,
                (gfx_sprite_t*)enemy_tank_sprites[7].base_2_data,
                (gfx_sprite_t*)enemy_tank_sprites[7].base_3_data,
                (gfx_sprite_t*)enemy_tank_sprites[7].base_4_data,
                (gfx_sprite_t*)enemy_tank_sprites[7].base_5_data,
                (gfx_sprite_t*)enemy_tank_sprites[7].base_6_data,
                (gfx_sprite_t*)enemy_tank_sprites[7].base_7_data,
                (gfx_sprite_t*)enemy_tank_sprites[7].base_8_data,
                (gfx_sprite_t*)enemy_tank_sprites[7].base_9_data,
                (gfx_sprite_t*)enemy_tank_sprites[7].base_10_data,
                (gfx_sprite_t*)enemy_tank_sprites[7].base_11_data,
                (gfx_sprite_t*)enemy_tank_sprites[7].base_12_data,
                (gfx_sprite_t*)enemy_tank_sprites[7].base_13_data,
                (gfx_sprite_t*)enemy_tank_sprites[7].base_14_data,
                (gfx_sprite_t*)enemy_tank_sprites[7].base_15_data,
        },
        {
                (gfx_sprite_t*)enemy_tank_sprites[8].base_0_data,
                (gfx_sprite_t*)enemy_tank_sprites[8].base_1_data,
                (gfx_sprite_t*)enemy_tank_sprites[8].base_2_data,
                (gfx_sprite_t*)enemy_tank_sprites[8].base_3_data,
                (gfx_sprite_t*)enemy_tank_sprites[8].base_4_data,
                (gfx_sprite_t*)enemy_tank_sprites[8].base_5_data,
                (gfx_sprite_t*)enemy_tank_sprites[8].base_6_data,
                (gfx_sprite_t*)enemy_tank_sprites[8].base_7_data,
                (gfx_sprite_t*)enemy_tank_sprites[8].base_8_data,
                (gfx_sprite_t*)enemy_tank_sprites[8].base_9_data,
                (gfx_sprite_t*)enemy_tank_sprites[8].base_10_data,
                (gfx_sprite_t*)enemy_tank_sprites[8].base_11_data,
                (gfx_sprite_t*)enemy_tank_sprites[8].base_12_data,
                (gfx_sprite_t*)enemy_tank_sprites[8].base_13_data,
                (gfx_sprite_t*)enemy_tank_sprites[8].base_14_data,
                (gfx_sprite_t*)enemy_tank_sprites[8].base_15_data,
        }
};

gfx_sprite_t * const tank_turrets[NUM_TANK_TYPES][16] = {
        {
                pl_turret_0,
                pl_turret_1,
                pl_turret_2,
                pl_turret_3,
                pl_turret_4,
                pl_turret_5,
                pl_turret_6,
                pl_turret_7,
                pl_turret_8,
                (gfx_sprite_t*)pl_turret_9_data,
                (gfx_sprite_t*)pl_turret_10_data,
                (gfx_sprite_t*)pl_turret_11_data,
                (gfx_sprite_t*)pl_turret_12_data,
                (gfx_sprite_t*)pl_turret_13_data,
                (gfx_sprite_t*)pl_turret_14_data,
                (gfx_sprite_t*)pl_turret_15_data,
        },
        {
                (gfx_sprite_t*)enemy_tank_sprites[0].turret_0_data,
                (gfx_sprite_t*)enemy_tank_sprites[0].turret_1_data,
                (gfx_sprite_t*)enemy_tank_sprites[0].turret_2_data,
                (gfx_sprite_t*)enemy_tank_sprites[0].turret_3_data,
                (gfx_sprite_t*)enemy_tank_sprites[0].turret_4_data,
                (gfx_sprite_t*)enemy_tank_sprites[0].turret_5_data,
                (gfx_sprite_t*)enemy_tank_sprites[0].turret_6_data,
                (gfx_sprite_t*)enemy_tank_sprites[0].turret_7_data,
                (gfx_sprite_t*)enemy_tank_sprites[0].turret_8_data,
                (gfx_sprite_t*)enemy_tank_sprites[0].turret_9_data,
                (gfx_sprite_t*)enemy_tank_sprites[0].turret_10_data,
                (gfx_sprite_t*)enemy_tank_sprites[0].turret_11_data,
                (gfx_sprite_t*)enemy_tank_sprites[0].turret_12_data,
                (gfx_sprite_t*)enemy_tank_sprites[0].turret_13_data,
                (gfx_sprite_t*)enemy_tank_sprites[0].turret_14_data,
                (gfx_sprite_t*)enemy_tank_sprites[0].turret_15_data,
        },
        {
                (gfx_sprite_t*)enemy_tank_sprites[1].turret_0_data,
                (gfx_sprite_t*)enemy_tank_sprites[1].turret_1_data,
                (gfx_sprite_t*)enemy_tank_sprites[1].turret_2_data,
                (gfx_sprite_t*)enemy_tank_sprites[1].turret_3_data,
                (gfx_sprite_t*)enemy_tank_sprites[1].turret_4_data,
                (gfx_sprite_t*)enemy_tank_sprites[1].turret_5_data,
                (gfx_sprite_t*)enemy_tank_sprites[1].turret_6_data,
                (gfx_sprite_t*)enemy_tank_sprites[1].turret_7_data,
                (gfx_sprite_t*)enemy_tank_sprites[1].turret_8_data,
                (gfx_sprite_t*)enemy_tank_sprites[1].turret_9_data,
                (gfx_sprite_t*)enemy_tank_sprites[1].turret_10_data,
                (gfx_sprite_t*)enemy_tank_sprites[1].turret_11_data,
                (gfx_sprite_t*)enemy_tank_sprites[1].turret_12_data,
                (gfx_sprite_t*)enemy_tank_sprites[1].turret_13_data,
                (gfx_sprite_t*)enemy_tank_sprites[1].turret_14_data,
                (gfx_sprite_t*)enemy_tank_sprites[1].turret_15_data,
        },
        {
                (gfx_sprite_t*)enemy_tank_sprites[2].turret_0_data,
                (gfx_sprite_t*)enemy_tank_sprites[2].turret_1_data,
                (gfx_sprite_t*)enemy_tank_sprites[2].turret_2_data,
                (gfx_sprite_t*)enemy_tank_sprites[2].turret_3_data,
                (gfx_sprite_t*)enemy_tank_sprites[2].turret_4_data,
                (gfx_sprite_t*)enemy_tank_sprites[2].turret_5_data,
                (gfx_sprite_t*)enemy_tank_sprites[2].turret_6_data,
                (gfx_sprite_t*)enemy_tank_sprites[2].turret_7_data,
                (gfx_sprite_t*)enemy_tank_sprites[2].turret_8_data,
                (gfx_sprite_t*)enemy_tank_sprites[2].turret_9_data,
                (gfx_sprite_t*)enemy_tank_sprites[2].turret_10_data,
                (gfx_sprite_t*)enemy_tank_sprites[2].turret_11_data,
                (gfx_sprite_t*)enemy_tank_sprites[2].turret_12_data,
                (gfx_sprite_t*)enemy_tank_sprites[2].turret_13_data,
                (gfx_sprite_t*)enemy_tank_sprites[2].turret_14_data,
                (gfx_sprite_t*)enemy_tank_sprites[2].turret_15_data,
        },
        {
                (gfx_sprite_t*)enemy_tank_sprites[3].turret_0_data,
                (gfx_sprite_t*)enemy_tank_sprites[3].turret_1_data,
                (gfx_sprite_t*)enemy_tank_sprites[3].turret_2_data,
                (gfx_sprite_t*)enemy_tank_sprites[3].turret_3_data,
                (gfx_sprite_t*)enemy_tank_sprites[3].turret_4_data,
                (gfx_sprite_t*)enemy_tank_sprites[3].turret_5_data,
                (gfx_sprite_t*)enemy_tank_sprites[3].turret_6_data,
                (gfx_sprite_t*)enemy_tank_sprites[3].turret_7_data,
                (gfx_sprite_t*)enemy_tank_sprites[3].turret_8_data,
                (gfx_sprite_t*)enemy_tank_sprites[3].turret_9_data,
                (gfx_sprite_t*)enemy_tank_sprites[3].turret_10_data,
                (gfx_sprite_t*)enemy_tank_sprites[3].turret_11_data,
                (gfx_sprite_t*)enemy_tank_sprites[3].turret_12_data,
                (gfx_sprite_t*)enemy_tank_sprites[3].turret_13_data,
                (gfx_sprite_t*)enemy_tank_sprites[3].turret_14_data,
                (gfx_sprite_t*)enemy_tank_sprites[3].turret_15_data,
        },
        {
                (gfx_sprite_t*)enemy_tank_sprites[4].turret_0_data,
                (gfx_sprite_t*)enemy_tank_sprites[4].turret_1_data,
                (gfx_sprite_t*)enemy_tank_sprites[4].turret_2_data,
                (gfx_sprite_t*)enemy_tank_sprites[4].turret_3_data,
                (gfx_sprite_t*)enemy_tank_sprites[4].turret_4_data,
                (gfx_sprite_t*)enemy_tank_sprites[4].turret_5_data,
                (gfx_sprite_t*)enemy_tank_sprites[4].turret_6_data,
                (gfx_sprite_t*)enemy_tank_sprites[4].turret_7_data,
                (gfx_sprite_t*)enemy_tank_sprites[4].turret_8_data,
                (gfx_sprite_t*)enemy_tank_sprites[4].turret_9_data,
                (gfx_sprite_t*)enemy_tank_sprites[4].turret_10_data,
                (gfx_sprite_t*)enemy_tank_sprites[4].turret_11_data,
                (gfx_sprite_t*)enemy_tank_sprites[4].turret_12_data,
                (gfx_sprite_t*)enemy_tank_sprites[4].turret_13_data,
                (gfx_sprite_t*)enemy_tank_sprites[4].turret_14_data,
                (gfx_sprite_t*)enemy_tank_sprites[4].turret_15_data,
        },
        {
                (gfx_sprite_t*)enemy_tank_sprites[5].turret_0_data,
                (gfx_sprite_t*)enemy_tank_sprites[5].turret_1_data,
                (gfx_sprite_t*)enemy_tank_sprites[5].turret_2_data,
                (gfx_sprite_t*)enemy_tank_sprites[5].turret_3_data,
                (gfx_sprite_t*)enemy_tank_sprites[5].turret_4_data,
                (gfx_sprite_t*)enemy_tank_sprites[5].turret_5_data,
                (gfx_sprite_t*)enemy_tank_sprites[5].turret_6_data,
                (gfx_sprite_t*)enemy_tank_sprites[5].turret_7_data,
                (gfx_sprite_t*)enemy_tank_sprites[5].turret_8_data,
                (gfx_sprite_t*)enemy_tank_sprites[5].turret_9_data,
                (gfx_sprite_t*)enemy_tank_sprites[5].turret_10_data,
                (gfx_sprite_t*)enemy_tank_sprites[5].turret_11_data,
                (gfx_sprite_t*)enemy_tank_sprites[5].turret_12_data,
                (gfx_sprite_t*)enemy_tank_sprites[5].turret_13_data,
                (gfx_sprite_t*)enemy_tank_sprites[5].turret_14_data,
                (gfx_sprite_t*)enemy_tank_sprites[5].turret_15_data,
        },
        {
                (gfx_sprite_t*)enemy_tank_sprites[6].turret_0_data,
                (gfx_sprite_t*)enemy_tank_sprites[6].turret_1_data,
                (gfx_sprite_t*)enemy_tank_sprites[6].turret_2_data,
                (gfx_sprite_t*)enemy_tank_sprites[6].turret_3_data,
                (gfx_sprite_t*)enemy_tank_sprites[6].turret_4_data,
                (gfx_sprite_t*)enemy_tank_sprites[6].turret_5_data,
                (gfx_sprite_t*)enemy_tank_sprites[6].turret_6_data,
                (gfx_sprite_t*)enemy_tank_sprites[6].turret_7_data,
                (gfx_sprite_t*)enemy_tank_sprites[6].turret_8_data,
                (gfx_sprite_t*)enemy_tank_sprites[6].turret_9_data,
                (gfx_sprite_t*)enemy_tank_sprites[6].turret_10_data,
                (gfx_sprite_t*)enemy_tank_sprites[6].turret_11_data,
                (gfx_sprite_t*)enemy_tank_sprites[6].turret_12_data,
                (gfx_sprite_t*)enemy_tank_sprites[6].turret_13_data,
                (gfx_sprite_t*)enemy_tank_sprites[6].turret_14_data,
                (gfx_sprite_t*)enemy_tank_sprites[6].turret_15_data,
        },
        {
                (gfx_sprite_t*)enemy_tank_sprites[7].turret_0_data,
                (gfx_sprite_t*)enemy_tank_sprites[7].turret_1_data,
                (gfx_sprite_t*)enemy_tank_sprites[7].turret_2_data,
                (gfx_sprite_t*)enemy_tank_sprites[7].turret_3_data,
                (gfx_sprite_t*)enemy_tank_sprites[7].turret_4_data,
                (gfx_sprite_t*)enemy_tank_sprites[7].turret_5_data,
                (gfx_sprite_t*)enemy_tank_sprites[7].turret_6_data,
                (gfx_sprite_t*)enemy_tank_sprites[7].turret_7_data,
                (gfx_sprite_t*)enemy_tank_sprites[7].turret_8_data,
                (gfx_sprite_t*)enemy_tank_sprites[7].turret_9_data,
                (gfx_sprite_t*)enemy_tank_sprites[7].turret_10_data,
                (gfx_sprite_t*)enemy_tank_sprites[7].turret_11_data,
                (gfx_sprite_t*)enemy_tank_sprites[7].turret_12_data,
                (gfx_sprite_t*)enemy_tank_sprites[7].turret_13_data,
                (gfx_sprite_t*)enemy_tank_sprites[7].turret_14_data,
                (gfx_sprite_t*)enemy_tank_sprites[7].turret_15_data,
        },
        {
                (gfx_sprite_t*)enemy_tank_sprites[8].turret_0_data,
                (gfx_sprite_t*)enemy_tank_sprites[8].turret_1_data,
                (gfx_sprite_t*)enemy_tank_sprites[8].turret_2_data,
                (gfx_sprite_t*)enemy_tank_sprites[8].turret_3_data,
                (gfx_sprite_t*)enemy_tank_sprites[8].turret_4_data,
                (gfx_sprite_t*)enemy_tank_sprites[8].turret_5_data,
                (gfx_sprite_t*)enemy_tank_sprites[8].turret_6_data,
                (gfx_sprite_t*)enemy_tank_sprites[8].turret_7_data,
                (gfx_sprite_t*)enemy_tank_sprites[8].turret_8_data,
                (gfx_sprite_t*)enemy_tank_sprites[8].turret_9_data,
                (gfx_sprite_t*)enemy_tank_sprites[8].turret_10_data,
                (gfx_sprite_t*)enemy_tank_sprites[8].turret_11_data,
                (gfx_sprite_t*)enemy_tank_sprites[8].turret_12_data,
                (gfx_sprite_t*)enemy_tank_sprites[8].turret_13_data,
                (gfx_sprite_t*)enemy_tank_sprites[8].turret_14_data,
                (gfx_sprite_t*)enemy_tank_sprites[8].turret_15_data,
        }
};

const uint8_t base_x_offsets[16] =  {
        pl_base_0_offset_x,
        pl_base_1_offset_x,
        pl_base_2_offset_x,
        pl_base_3_offset_x,
        pl_base_4_offset_x,
        pl_base_5_offset_x,
        pl_base_6_offset_x,
        pl_base_7_offset_x,
        pl_base_8_offset_x,
        tank_sprite_total_width - pl_base_7_offset_x - pl_base_7_width,
        tank_sprite_total_width - pl_base_6_offset_x - pl_base_6_width,
        tank_sprite_total_width - pl_base_5_offset_x - pl_base_5_width,
        tank_sprite_total_width - pl_base_4_offset_x - pl_base_4_width,
        tank_sprite_total_width - pl_base_3_offset_x - pl_base_3_width,
        tank_sprite_total_width - pl_base_2_offset_x - pl_base_2_width,
        tank_sprite_total_width - pl_base_1_offset_x - pl_base_1_width,
};

const uint8_t base_y_offsets[16] =  {
        pl_base_0_offset_y,
        pl_base_1_offset_y,
        pl_base_2_offset_y,
        pl_base_3_offset_y,
        pl_base_4_offset_y,
        pl_base_5_offset_y,
        pl_base_6_offset_y,
        pl_base_7_offset_y,
        pl_base_8_offset_y,
        pl_base_7_offset_y,
        pl_base_6_offset_y,
        pl_base_5_offset_y,
        pl_base_4_offset_y,
        pl_base_3_offset_y,
        pl_base_2_offset_y,
        pl_base_1_offset_y,
};

const uint8_t turret_x_offsets[16] =  {
        pl_turret_0_offset_x,
        pl_turret_1_offset_x,
        pl_turret_2_offset_x,
        pl_turret_3_offset_x,
        pl_turret_4_offset_x,
        pl_turret_5_offset_x,
        pl_turret_6_offset_x,
        pl_turret_7_offset_x,
        pl_turret_8_offset_x,
        tank_sprite_total_width - pl_turret_7_offset_x - pl_turret_7_width,
        tank_sprite_total_width - pl_turret_6_offset_x - pl_turret_6_width,
        tank_sprite_total_width - pl_turret_5_offset_x - pl_turret_5_width,
        tank_sprite_total_width - pl_turret_4_offset_x - pl_turret_4_width,
        tank_sprite_total_width - pl_turret_3_offset_x - pl_turret_3_width,
        tank_sprite_total_width - pl_turret_2_offset_x - pl_turret_2_width,
        tank_sprite_total_width - pl_turret_1_offset_x - pl_turret_1_width,
};

const uint8_t turret_y_offsets[16] =  {
        pl_turret_0_offset_y,
        pl_turret_1_offset_y,
        pl_turret_2_offset_y,
        pl_turret_3_offset_y,
        pl_turret_4_offset_y,
        pl_turret_5_offset_y,
        pl_turret_6_offset_y,
        pl_turret_7_offset_y,
        pl_turret_8_offset_y,
        pl_turret_7_offset_y,
        pl_turret_6_offset_y,
        pl_turret_5_offset_y,
        pl_turret_4_offset_y,
        pl_turret_3_offset_y,
        pl_turret_2_offset_y,
        pl_turret_1_offset_y,
};
